<script setup lang="ts">
import type { Habit } from '#shared/domain/types'
const model=defineModel<Habit[]>({required:true});defineProps<{days:number[]}>()
const {locale}=useI18n();const en=computed(()=>locale.value==='en');const text=(th:string,english:string)=>en.value?english:th
const weekdays=computed(()=>en.value?['Sun','Mon','Tue','Wed','Thu','Fri','Sat']:['อา','จ','อ','พ','พฤ','ศ','ส'])
function toggle(habit:Habit,index:number){const days=habit.recurrence?.type==='weekly'?habit.recurrence.weekdays:[0,1,2,3,4,5,6];habit.recurrence={type:'weekly',weekdays:days.includes(index)?days.filter(day=>day!==index):[...days,index].sort()}}
function add(){model.value.push({id:crypto.randomUUID(),title:'',description:'',slot:'morning',active:true,createdAt:new Date().toISOString()})}
</script>
<template>
  <section class="mt-6"><h3 class="section-title">{{ text('กิจวัตรของคุณ','Your habits') }}</h3><p class="help">{{ text('แก้หรือเก็บเข้าคลังมีผลวันถัดไป ประวัติเดิมยังอยู่','Edits and archiving start tomorrow. Existing history stays intact.') }}</p>
    <article v-for="habit in model" :key="habit.id" class="habit-editor"><label class="form-label">{{ text('ชื่อกิจวัตร','Habit name') }}<input v-model="habit.title" class="field" maxlength="80" required/></label><label class="form-label">{{ text('รายละเอียด','Description') }}<input v-model="habit.description" class="field" maxlength="200"/></label><div class="grid gap-3 sm:grid-cols-2"><label class="form-label">{{ text('ช่วงวัน','Day period') }}<select v-model="habit.slot" class="field"><option value="morning">{{ text('เช้า','Morning') }}</option><option value="afternoon">{{ text('ระหว่างวัน','During the day') }}</option><option value="evening">{{ text('เย็น','Evening') }}</option></select></label><label class="form-label">{{ text('เวลา (ว่าง = ใช้ค่าโมดูล)','Time (blank uses module setting)') }}<input v-model="habit.time" class="field" maxlength="20"/></label></div><label class="setting-row"><span>{{ text('ใช้วันทำซ้ำจากโมดูล','Use module weekdays') }}</span><input type="checkbox" :checked="!habit.recurrence" @change="habit.recurrence=($event.target as HTMLInputElement).checked?undefined:{type:'weekly',weekdays:[...days]}"/></label><div class="flex flex-wrap gap-2"><button v-for="(label,index) in weekdays" :key="index" type="button" class="day-chip" :class="{chosen:!habit.recurrence?days.includes(index):habit.recurrence.type==='daily'||habit.recurrence.weekdays.includes(index)}" :aria-pressed="!habit.recurrence?days.includes(index):habit.recurrence.type==='daily'||habit.recurrence.weekdays.includes(index)" :disabled="!habit.recurrence" :aria-label="`${habit.title} ${label}`" @click="toggle(habit,index)">{{ label }}</button></div><label class="setting-row"><span>{{ habit.active?text('เปิดใช้งาน','Active'):text('เก็บเข้าคลัง','Archived') }}</span><input v-model="habit.active" type="checkbox"/></label></article>
    <button type="button" class="btn-quiet mt-3" @click="add"><UIcon name="i-lucide-plus"/>{{ text('เพิ่มกิจวัตรเอง','Add your own habit') }}</button>
  </section>
</template>
<style scoped>.habit-editor{display:grid;gap:12px;padding:20px 0;border-bottom:1px solid var(--mh-line)}</style>
