<script setup lang="ts">
import type { ModuleId, MyhabitSettings, Goal } from '#shared/domain/types'
import { clone, resolveModule } from '#shared/domain/settings'
import { unitSets } from '#shared/domain/converters'
const props=defineProps<{module:ModuleId;goals:Goal[]}>();const model=defineModel<MyhabitSettings>({required:true})
const {locale}=useI18n();const en=computed(()=>locale.value==='en');const text=(th:string,english:string)=>en.value?english:th
type Field={key:string;th:string;en:string;kind:'days'|'time'|'number'|'select'|'check'|'text';global?:boolean;min?:number;max?:number;step?:number;options?:{id:string|number;th:string;en:string}[]}
const raw=computed(()=>model.value.modules[props.module] as Record<string,any>);const resolved=computed(()=>resolveModule(model.value,props.module) as Record<string,any>)
const weekdays=computed(()=>en.value?['Sun','Mon','Tue','Wed','Thu','Fri','Sat']:['อา','จ','อ','พ','พฤ','ศ','ส'])
const common:Field[]=[{key:'weekdays',th:'วันทำซ้ำ',en:'Repeating weekdays',kind:'days',global:true},{key:'time',th:'เวลาเริ่มต้น',en:'Default time',kind:'time',global:true},{key:'remindersEnabled',th:'เปิดการเตือน',en:'Enable reminders',kind:'check',global:true},{key:'reminderTime',th:'เวลาเตือน',en:'Reminder time',kind:'time',global:true}]
const specific:Record<ModuleId,Field[]>={
 habits:[{key:'passThreshold',th:'จำนวนกิจวัตรเพื่อผ่าน',en:'Habit pass threshold',kind:'number',min:1,max:30,global:true}],
 tasks:[{key:'defaultPriority',th:'ความสำคัญเริ่มต้น',en:'Default priority',kind:'select',options:[{id:'low',th:'เบา',en:'Low'},{id:'med',th:'ปกติ',en:'Normal'},{id:'high',th:'สำคัญ',en:'High'}]},{key:'defaultRecurrence',th:'ประเภทงานเริ่มต้น',en:'Default task schedule',kind:'select',options:[{id:'once',th:'ครั้งเดียว',en:'Once'},{id:'daily',th:'ทุกวัน',en:'Daily'},{id:'weekly',th:'ตามวันทำซ้ำ',en:'Selected weekdays'}]}],
 goals:[],mood:[],focus:[{key:'focusMinutes',th:'นาทีโฟกัส',en:'Focus minutes',kind:'number',min:1,max:180,global:true},{key:'breakMinutes',th:'นาทีพัก',en:'Break minutes',kind:'number',min:1,max:60,global:true},{key:'targetMinutes',th:'เป้านาทีรายวัน',en:'Daily target minutes',kind:'number',min:1,max:1440}],
 finance:[{key:'defaultKind',th:'ประเภทรายการเริ่มต้น',en:'Default entry type',kind:'select',options:[{id:'expense',th:'รายจ่าย',en:'Expense'},{id:'income',th:'รายรับ',en:'Income'}]},{key:'defaultCategory',th:'หมวดหมู่เริ่มต้น',en:'Default category',kind:'text'}],
 progress:[{key:'weekStartsOn',th:'วันเริ่มสัปดาห์',en:'Week starts on',kind:'select',options:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((en,id)=>({id,th:['อาทิตย์','จันทร์','อังคาร','พุธ','พฤหัส','ศุกร์','เสาร์'][id]!,en}))},{key:'showHeatmap',th:'แสดง heatmap ทั้งปี',en:'Show year heatmap',kind:'check'}],
 tools:[{key:'peopleCount',th:'จำนวนคนเริ่มต้น',en:'Default people',kind:'number',min:1,max:30},{key:'serviceEnabled',th:'รวมค่าบริการเริ่มต้น',en:'Service charge by default',kind:'check'},{key:'vatEnabled',th:'รวม VAT เริ่มต้น',en:'VAT by default',kind:'check'},{key:'serviceRate',th:'อัตราค่าบริการ (0–1)',en:'Service rate (0–1)',kind:'number',min:0,max:1,step:.01},{key:'vatRate',th:'อัตรา VAT (0–1)',en:'VAT rate (0–1)',kind:'number',min:0,max:1,step:.01}]
}
const fields=computed(()=>[...(['progress','tools'].includes(props.module)?[]:common),...specific[props.module]])
function toggle(key:string,enabled:boolean){if(enabled)raw.value[key]=clone(resolved.value[key]);else delete raw.value[key]}
function update(field:Field,event:Event){const input=event.target as HTMLInputElement;raw.value[field.key]=field.kind==='check'?input.checked:field.kind==='number'||field.key==='weekStartsOn'?Number(input.value):input.value}
function toggleDay(index:number){const days:number[]=resolved.value.weekdays;raw.value.weekdays=days.includes(index)?days.filter(day=>day!==index):[...days,index].sort()}
function pair(kind:string){return model.value.modules.tools.unitPairs?.[kind]??{from:unitSets[kind as keyof typeof unitSets][0]?.id??'',to:unitSets[kind as keyof typeof unitSets][1]?.id??''}}
function setPair(kind:string,key:'from'|'to',event:Event){model.value.modules.tools.unitPairs??={};model.value.modules.tools.unitPairs[kind]={...pair(kind),[key]:(event.target as HTMLSelectElement).value}}
</script>
<template>
  <div class="grid gap-1">
    <label v-if="['habits','tasks','goals','focus','mood'].includes(module)" class="setting-row"><span>{{ text('แสดงในหน้าวันนี้','Include in Today') }}</span><input type="checkbox" :checked="resolved.inToday" @change="raw.inToday=($event.target as HTMLInputElement).checked"/></label>
    <div v-for="field in fields" :key="`${module}:${field.key}`" class="override-field">
      <div class="flex flex-wrap items-center justify-between gap-2"><label :for="`${module}-${field.key}`" class="text-sm font-medium">{{ en?field.en:field.th }}</label><label class="flex min-h-11 items-center gap-2 text-xs muted"><input type="checkbox" :aria-label="`${field.en} override`" :checked="raw[field.key]!==undefined" @change="toggle(field.key,($event.target as HTMLInputElement).checked)">{{ raw[field.key]===undefined?(field.global?text('ใช้ค่ารวม','Use global settings'):text('ใช้ค่าเริ่มต้น','Use default')):text('กำหนดเฉพาะ','Module override') }}</label></div>
      <div v-if="field.kind==='days'" class="flex flex-wrap gap-2"><button v-for="(label,index) in weekdays" :key="index" type="button" class="day-chip" :class="{chosen:resolved.weekdays.includes(index)}" :aria-pressed="resolved.weekdays.includes(index)" :disabled="raw[field.key]===undefined" @click="toggleDay(index)">{{ label }}</button></div>
      <select v-else-if="field.kind==='select'" :id="`${module}-${field.key}`" class="field" :value="resolved[field.key]" :disabled="raw[field.key]===undefined" @change="update(field,$event)"><option v-for="option in field.options" :key="option.id" :value="option.id">{{ en?option.en:option.th }}</option></select>
      <label v-else-if="field.kind==='check'" class="setting-row"><span class="text-sm muted">{{ resolved[field.key]?text('เปิด','On'):text('ปิด','Off') }}</span><input :id="`${module}-${field.key}`" type="checkbox" :checked="resolved[field.key]" :disabled="raw[field.key]===undefined" @change="update(field,$event)"/></label>
      <input v-else :id="`${module}-${field.key}`" class="field" :type="field.kind" :value="resolved[field.key]" :min="field.min" :max="field.max" :step="field.step??1" maxlength="60" :disabled="raw[field.key]===undefined" @change="update(field,$event)"/>
    </div>
    <div v-if="module==='goals'" class="grid gap-2 mt-3"><h3 class="section-title">{{ text('เป้าหมายที่ต้องเช็กอิน','Goals to check in') }}</h3><label v-for="goal in goals.filter(item=>!item.archived)" :key="goal.id" class="setting-row"><span>{{ goal.title }}</span><input type="checkbox" :checked="resolved.goalIds.includes(goal.id)" @change="raw.goalIds=resolved.goalIds.includes(goal.id)?resolved.goalIds.filter((id:string)=>id!==goal.id):[...resolved.goalIds,goal.id]"/></label><p v-if="!goals.some(item=>!item.archived)" class="help">{{ text('เพิ่มเป้าหมายก่อนเปิดเช็กอินรายวัน','Create a goal before enabling daily check-ins.') }}</p><NuxtLink to="/goals" class="settings-link accent">{{ text('จัดการเป้าหมาย','Manage goals') }}</NuxtLink></div>
    <p v-if="module==='focus'" class="help">{{ text('เวลาใหม่ใช้ใน session ถัดไป ไม่รีเซ็ต session ที่กำลังทำ','New durations apply to the next session without resetting an active session.') }}</p>
    <p v-if="module==='mood'" class="help">{{ text('บันทึกอารมณ์หนึ่งครั้งถือว่าเช็กอินสำเร็จ การอัปเดตไม่สร้างรายการซ้ำ','One saved mood entry completes the day. Updates replace it rather than creating duplicates.') }}</p>
    <p v-if="module==='finance'" class="help">THB · {{ text('รายการที่เชื่อมเป้าหมายใช้ยอดชุดเดียวกัน','Goal-linked entries use the same ledger records.') }}</p>
    <NuxtLink v-if="module==='tasks'" to="/tasks" class="settings-link accent mt-4">{{ text('จัดการงานและงานย่อย','Manage tasks and subtasks') }}</NuxtLink>
    <div v-if="module==='tools'" class="grid gap-4 mt-5"><h3 class="section-title">{{ text('คู่หน่วยเริ่มต้น','Default conversion units') }}</h3><div v-for="(units,kind) in unitSets" :key="kind" class="grid gap-2"><div class="flex justify-between items-center"><span class="text-sm">{{ kind }}</span><button v-if="model.modules.tools.unitPairs?.[kind]" type="button" class="min-h-11 text-xs accent" @click="delete model.modules.tools.unitPairs[kind]">{{ text('ใช้ค่าเริ่มต้น','Use default') }}</button></div><div class="grid grid-cols-2 gap-3"><select class="field" :aria-label="`${kind} from`" :value="pair(kind).from" @change="setPair(kind,'from',$event)"><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ unit.label }}</option></select><select class="field" :aria-label="`${kind} to`" :value="pair(kind).to" @change="setPair(kind,'to',$event)"><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ unit.label }}</option></select></div></div><p class="help">{{ text('ไม่เก็บชื่อคน เลข PromptPay หรือข้อมูลสุขภาพในค่าตั้งต้น','Defaults do not store names, PromptPay IDs or health inputs.') }}</p></div>
  </div>
</template>
<style scoped>.override-field{padding:12px 0;border-bottom:1px solid var(--mh-line)}</style>
