<script setup lang="ts">
import type { MoodEntry } from '#shared/domain/types'
import { localDateKey, isDateKey } from '#shared/domain/dates'
const route=useRoute();const {t,locale}=useI18n();const {state,touch,initialized}=useWorkspace();const today=computed(()=>{const current=localDateKey(new Date(),state.value.settings.timezone);return isDateKey(route.query.date)&&route.query.date<=current?route.query.date:current});const mood=ref<MoodEntry['mood']>('calm');const energy=ref(3);const gratitude=ref('')
const {notify}=useFeedback();const vent=ref('')
const current=computed(()=>state.value.moodEntries.find(entry=>entry.date===today.value))
function save(){if(!initialized.value)return;const entry:MoodEntry={...current.value,date:today.value,mood:mood.value,energy:energy.value,gratitude:gratitude.value.trim()||undefined,vent:vent.value.trim()||undefined};state.value.moodEntries=state.value.moodEntries.filter(item=>item.date!==today.value);state.value.moodEntries.push(entry);touch();notify('บันทึกความรู้สึกแล้ว','Mood saved')}
watch(current,value=>{mood.value=value?.mood??'calm';energy.value=value?.energy??3;gratitude.value=value?.gratitude??'';vent.value=value?.vent??''},{immediate:true})
const options:{key:MoodEntry['mood'];label:string;en:string;icon:string}[]=[{key:'happy',label:'สดใส',en:'Happy',icon:'i-lucide-sun'},{key:'calm',label:'สงบ',en:'Calm',icon:'i-lucide-leaf'},{key:'tired',label:'เหนื่อย',en:'Tired',icon:'i-lucide-battery-low'},{key:'sad',label:'เศร้า',en:'Sad',icon:'i-lucide-cloud-rain'},{key:'stressed',label:'เครียด',en:'Stressed',icon:'i-lucide-waves'}]
const text=(th:string,english:string)=>locale.value==='en'?english:th
function removeEntry(entry:MoodEntry){state.value.moodEntries=state.value.moodEntries.filter(row=>row.date!==entry.date);touch();notify('ลบบันทึกแล้ว','Check-in removed',()=>{if(!state.value.moodEntries.some(row=>row.date===entry.date))state.value.moodEntries.push(entry);touch()})}
</script>
<template>
  <div class="page-wrap mx-auto grid max-w-3xl gap-5">
    <header><h1 class="page-title">{{ text('แวะฟังความรู้สึก','Make room for your feelings') }}</h1><p class="mb-0 mt-1 text-sm muted">{{ text('บันทึกไว้ดูเอง ไม่ต้องให้คะแนนว่าวันนี้ดีหรือแย่','A private record without judging your day') }}</p></header>
    <p class="m-0 text-sm muted">{{ today }}</p><form class="surface grid gap-5 p-5" @submit.prevent="save"><fieldset class="grid gap-3 border-0 p-0"><legend class="mb-3 text-sm font-semibold">{{ text('ตอนนี้รู้สึกอย่างไร','How are you feeling now?') }}</legend><div class="grid grid-cols-2 gap-2 sm:grid-cols-5"><button v-for="item in options" :key="item.key" type="button" class="mood-option grid min-h-20 justify-items-center gap-2 rounded-2xl border p-3 text-sm" :class="{chosen:mood===item.key}" :aria-pressed="mood===item.key" @click="mood=item.key"><UIcon :name="item.icon" class="size-6"/>{{ locale==='en'?item.en:item.label }}</button></div></fieldset><label class="grid gap-2 text-sm font-semibold">{{ t('energy') }} · {{ energy }}/5<input v-model.number="energy" type="range" min="1" max="5" class="w-full accent-[var(--mh-accent)]"/></label><label class="grid gap-2 text-sm font-semibold">{{ t('gratitude') }} <input v-model="gratitude" class="field" maxlength="200"/></label><label class="form-label">{{ text('สิ่งที่อยากเขียนไว้ (ไม่บังคับ)','What is on your mind? (optional)') }}<textarea v-model="vent" class="field" rows="3" maxlength="2000"/></label><button class="btn-primary justify-self-start" :disabled="!initialized"><UIcon name="i-lucide-book-heart"/>{{ current?text('อัปเดตบันทึกวันนี้','Update today’s entry'):t('save') }}</button><p v-if="current" class="m-0 text-xs muted">{{ text('วันนี้บันทึกไว้แล้ว','Saved for this day') }} · {{ current.mood }} · {{ t('energy') }} {{ current.energy }}/5</p></form>
    <section class="surface p-4"><h2 class="section-title">{{ text('บันทึกย้อนหลัง','Previous check-ins') }}</h2><p v-if="!state.moodEntries.length" class="muted text-sm">{{ text('บันทึกครั้งแรก แล้วกลับมาดูความรู้สึกในแต่ละวันได้ที่นี่','Save your first check-in to see your daily feelings here.') }}</p><div v-for="entry in [...state.moodEntries].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,14)" :key="entry.date" class="flex justify-between gap-3 border-t py-3 text-sm" style="border-color:var(--mh-line)"><span>{{ entry.date }} · {{ locale==='en'?options.find(item=>item.key===entry.mood)?.en:options.find(item=>item.key===entry.mood)?.label }}<small v-if="entry.gratitude" class="block muted">{{ entry.gratitude }}</small></span><div class="flex flex-wrap items-center gap-2"><span class="text-xs muted">{{ t('energy') }} {{ entry.energy }}/5</span><NuxtLink :to="`/mood?date=${entry.date}`" class="btn-quiet !px-3" :aria-label="text('แก้ไขบันทึก','Edit check-in')"><UIcon name="i-lucide-pencil" class="size-4"/></NuxtLink><button class="btn-quiet danger-action !px-3" :aria-label="text('ลบบันทึก','Remove check-in')" @click="removeEntry(entry)"><UIcon name="i-lucide-x" class="size-4"/></button></div></div></section>
  </div>
</template>
<style scoped>.mood-option{background:var(--mh-surface);color:var(--mh-ink-soft);border-color:var(--mh-line)}.mood-option.chosen{background:var(--mh-accent-soft);color:var(--mh-accent);border-color:var(--mh-accent);font-weight:700}</style>
