<script setup lang="ts">
import { defaultState, type Habit, type ModuleId, type MyhabitSettings } from '#shared/domain/types'
import { clone, moduleRegistry, resolveModule, saveSettings, validateSettings } from '#shared/domain/settings'
import { ensureDailyPlan, saveHabitTemplate } from '#shared/domain/daily-plan'
import { localDateKey, dateOffset } from '#shared/domain/dates'
const {locale}=useI18n();const en=computed(()=>locale.value==='en');const text=(th:string,english:string)=>en.value?english:th
const {state,touch,user,status,syncNow,initialized}=useWorkspace();const route=useRoute();const router=useRouter()
const {available:installAvailable,installed,busy:installBusy,install}=useInstallApp()
const exportData=inject<()=>void>('myhabit-export');const importData=inject<()=>void>('myhabit-import')
const sections=['general','daily','modules','data'] as const
const section=ref<typeof sections[number]>(sections.includes(route.query.section as any)?route.query.section as any:'general')
const module=ref<ModuleId>(moduleRegistry.some(item=>item.id===route.query.module)?route.query.module as ModuleId:'habits')
const draft=ref<MyhabitSettings>(clone(state.value.settings));const habits=ref<Habit[]>([]);const baseline=ref('');const errors=ref<string[]>([]);const message=ref('');const saving=ref(false)
const labels=computed(()=>[text('ทั่วไป','General'),text('แผนรายวัน','Daily plan'),text('โมดูล','Modules'),text('ข้อมูลและบัญชี','Data & account')])
const today=computed(()=>localDateKey(new Date(),state.value.settings.timezone))
const weekdays=computed(()=>en.value?['Sun','Mon','Tue','Wed','Thu','Fri','Sat']:['อา','จ','อ','พ','พฤ','ศ','ส'])
const current=computed(()=>moduleRegistry.find(item=>item.id===module.value)!)
const dirty=computed(()=>JSON.stringify({settings:draft.value,habits:habits.value})!==baseline.value)
function load(){draft.value=clone(state.value.settings);habits.value=clone(state.value.habits.filter(habit=>!habit.onlyOn));baseline.value=JSON.stringify({settings:draft.value,habits:habits.value});errors.value=[];message.value=''}
watch(initialized,value=>{if(value)load()},{immediate:true})
watch(()=>route.query,query=>{if(sections.includes(query.section as any))section.value=query.section as any;if(moduleRegistry.some(item=>item.id===query.module))module.value=query.module as ModuleId})
function selectSection(value:typeof sections[number]){section.value=value;void router.replace({query:{section:value,...value==='modules'?{module:module.value}:{}}})}
function selectModule(){void router.replace({query:{section:'modules',module:module.value}})}
function toggleDay(index:number){const days=draft.value.dailyDefaults.weekdays;draft.value.dailyDefaults.weekdays=days.includes(index)?days.filter(day=>day!==index):[...days,index].sort()}
async function save(){
 errors.value=validateSettings(draft.value,state.value.goals)
 for(const habit of habits.value){if(!habit.title.trim()||habit.title.length>80)errors.value.push(text('กรอกชื่อกิจวัตรไม่เกิน 80 ตัวอักษร','Enter a habit name of up to 80 characters'));if(habit.active&&habit.recurrence?.type==='weekly'&&!habit.recurrence.weekdays.length)errors.value.push(text(`เลือกวันสำหรับ ${habit.title}`,`Choose weekdays for ${habit.title}`))}
 if(errors.value.length)return
 saving.value=true
 const reminders=draft.value.remindersEnabled||moduleRegistry.some(item=>(draft.value.modules[item.id] as any).remindersEnabled===true)
 if(reminders&&(!('Notification'in window)||Notification.permission!=='granted'&&await Notification.requestPermission()!=='granted')){errors.value=[text('ยังไม่ได้รับอนุญาตแจ้งเตือน ปิดการเตือนหรือตั้งสิทธิ์ในเบราว์เซอร์','Notifications are unavailable or blocked. Disable reminders or allow them in your browser.')];saving.value=false;return}
 ensureDailyPlan(state.value,today.value)
 for(const habit of habits.value){const original=state.value.habits.find(item=>item.id===habit.id);if(JSON.stringify(original)!==JSON.stringify(habit))saveHabitTemplate(state.value,{...habit,title:habit.title.trim()},today.value)}
 saveSettings(state.value,draft.value,today.value);touch();load();saving.value=false
 message.value=text(`บันทึกแล้ว · ตารางใหม่เริ่ม ${dateOffset(today.value,1)}`,`Saved · new schedules start ${dateOffset(today.value,1)}`)
}
</script>
<template>
 <div class="page-wrap grid gap-6"><header><h1 class="page-title">{{ text('ตั้งค่าให้เข้ากับคุณ','Make Myhabit yours') }}</h1><p class="mt-2 mb-0 text-sm muted">{{ text('ค่ารวมเป็นจุดเริ่มต้น แต่ละโมดูลปรับเพิ่มเติมได้','Start with global defaults. Adapt each module when needed.') }}</p></header>
 <div class="settings-layout">
  <nav class="settings-nav" :aria-label="text('หมวดตั้งค่า','Settings categories')"><button v-for="(id,index) in sections" :key="id" class="settings-category" :class="{active:section===id}" :aria-current="section===id?'page':undefined" @click="selectSection(id)">{{ labels[index] }}</button></nav>
  <label class="mobile-section text-sm">{{ text('หมวดตั้งค่า','Settings category') }}<select class="field mt-2" aria-label="Settings category" :value="section" @change="selectSection(($event.target as HTMLSelectElement).value as any)"><option v-for="(id,index) in sections" :key="id" :value="id">{{ labels[index] }}</option></select></label>
  <form class="settings-content surface" @submit.prevent="save"><fieldset :disabled="!initialized||saving" class="border-0 m-0 min-w-0 p-0">
   <section v-if="section==='general'" class="grid gap-5"><div><h2 class="section-title">{{ text('หน้าตาและภาษา','Appearance & language') }}</h2><p class="help">{{ text('ใช้ร่วมกันทั้ง Myhabit','Shared across Myhabit.') }}</p></div>
    <div class="grid gap-2"><button v-if="installAvailable" type="button" class="btn-quiet justify-self-start" :disabled="installBusy" @click="install"><UIcon name="i-lucide-download" class="size-4"/>{{ text('ติดตั้ง Myhabit','Install Myhabit') }}</button><p class="help">{{ installed?text('ติดตั้ง Myhabit แล้ว','Myhabit is installed.'):text('ติดตั้งได้ผ่านเมนูของเบราว์เซอร์ สำหรับ iPhone เลือกแชร์ แล้วเพิ่มไปยังหน้าจอโฮม','Install from your browser menu. On iPhone, use Share → Add to Home Screen.') }}</p></div><label class="form-label">{{ text('ธีม','Theme') }}<select v-model="draft.theme" class="field" aria-label="Theme"><option value="system">{{ text('ตามระบบ','System') }}</option><option value="light">{{ text('สว่าง','Light') }}</option><option value="dark">{{ text('มืด','Dark') }}</option></select></label>
    <div class="theme-preview" :class="`preview-${draft.theme}`"><span class="preview-dot"/><div><strong>{{ text('จังหวะที่สบายตา','A calmer daily rhythm') }}</strong><p class="m-0 text-sm">{{ text('พื้นอุ่น สีเขียวอ่อน และส้มดินเผา','Warm surfaces, soft sage and terracotta.') }}</p></div></div>
    <div class="grid gap-4 sm:grid-cols-2"><label class="form-label">{{ text('ภาษา','Language') }}<select v-model="draft.language" class="field" aria-label="Language"><option value="th">ไทย</option><option value="en">English</option></select></label><label class="form-label">Timezone<input v-model="draft.timezone" class="field" required placeholder="Asia/Bangkok"/></label></div>
   </section>
   <section v-if="section==='daily'" class="grid gap-5"><div><h2 class="section-title">{{ text('ค่าเริ่มต้นของแผนรายวัน','Daily plan defaults') }}</h2><p class="help">{{ text('ตารางใหม่เริ่มวันถัดไป วันที่บันทึกแล้วคงแผนเดิม','Schedule changes start tomorrow. Recorded days keep their original plan.') }}</p></div>
    <div><p class="form-label mb-2">{{ text('วันที่ทำซ้ำเริ่มต้น','Default repeating weekdays') }}</p><div class="flex flex-wrap gap-2"><button v-for="(label,index) in weekdays" :key="index" type="button" class="day-chip" :class="{chosen:draft.dailyDefaults.weekdays.includes(index)}" :aria-pressed="draft.dailyDefaults.weekdays.includes(index)" @click="toggleDay(index)">{{ label }}</button></div></div>
    <label class="form-label">{{ text('เวลาเริ่มต้นของเช็กอิน','Default check-in time') }}<input v-model="draft.dailyDefaults.time" class="field" type="time" required/></label>
    <div class="grid gap-4 sm:grid-cols-3"><label class="form-label">{{ text('จำนวนกิจวัตรเพื่อผ่าน','Habit pass threshold') }}<input v-model.number="draft.passThreshold" class="field" type="number" min="1" max="30" required/></label><label class="form-label">{{ text('โฟกัส (นาที)','Focus minutes') }}<input v-model.number="draft.focusMinutes" class="field" type="number" min="1" max="180" required/></label><label class="form-label">{{ text('พัก (นาที)','Break minutes') }}<input v-model.number="draft.breakMinutes" class="field" type="number" min="1" max="60" required/></label></div>
    <div class="settings-divider"><h3 class="section-title">{{ text('แสดงในหน้าวันนี้','Include in Today') }}</h3><label v-for="item in moduleRegistry.filter(item=>item.daily)" :key="item.id" class="setting-row"><span>{{ en?item.en:item.th }}</span><input type="checkbox" :aria-label="`${item.en} include in Today`" :checked="resolveModule(draft,item.id).inToday" @change="(draft.modules[item.id] as any).inToday=($event.target as HTMLInputElement).checked"/></label><p class="help">{{ text('เปิดเป้าหมายแล้วเลือกเป้าหมายที่ต้องเช็กอินในหมวดโมดูล','After enabling goals, select the goals under Modules.') }}</p></div>
    <div class="settings-divider"><h3 class="section-title">{{ text('การเตือนรวม','Global reminders') }}</h3><label class="setting-row"><span>{{ text('เปิดการเตือนขณะเปิดแอป','Remind me while the app is open') }}</span><input v-model="draft.remindersEnabled" type="checkbox"/></label><label class="form-label">{{ text('เวลาเตือน','Reminder time') }}<input v-model="draft.reminderTime" class="field" type="time" required/></label><p class="help">{{ text('รายการเวลาเดียวกันรวมเป็นการเตือนเดียว ปิดแอปแล้วไม่รับประกันการเตือน','Items at the same time share one notification. Reminders are not guaranteed after closing the app.') }}</p></div>
   </section>
   <section v-if="section==='modules'" class="grid gap-4"><label class="form-label">{{ text('เลือกโมดูล','Choose module') }}<select v-model="module" class="field" aria-label="Module" @change="selectModule"><option v-for="item in moduleRegistry" :key="item.id" :value="item.id">{{ en?item.en:item.th }}</option></select></label><div class="settings-divider flex items-center justify-between gap-3"><h2 class="section-title">{{ en?current.en:current.th }}</h2><button type="button" class="btn-quiet text-xs" @click="draft.modules[module]={}">{{ text('ใช้ค่าเริ่มต้น','Use defaults') }}</button></div>
    <ModulePreferences v-model="draft" :module="module" :goals="state.goals"/>
    <HabitTemplateEditor v-if="module==='habits'" v-model="habits" :days="resolveModule(draft,'habits').weekdays"/>
   </section>
   <section v-if="section==='data'" class="grid gap-5"><div><h2 class="section-title">{{ text('ข้อมูลและบัญชี','Data & account') }}</h2><p class="help">{{ user?.email??text('Guest · ข้อมูลบนอุปกรณ์นี้','Guest · data on this device') }} · {{ status }}</p></div><div class="flex flex-wrap gap-2"><button class="btn-quiet" type="button" @click="exportData?.()"><UIcon name="i-lucide-download"/>{{ text('สำรองข้อมูล','Export backup') }}</button><button class="btn-quiet" type="button" @click="importData?.()"><UIcon name="i-lucide-upload"/>{{ text('นำเข้าข้อมูล','Import backup') }}</button><button v-if="user" class="btn-quiet" type="button" @click="syncNow()">{{ text('ซิงก์ตอนนี้','Sync now') }}</button></div><p class="help">{{ text('ไฟล์ v3 เก็บแผนและค่าตั้งต้น ระบบอ่าน v2 และข้อมูลเดิมได้โดยรักษาประวัติ','v3 backups include plans and settings. v2 and legacy backups retain their history.') }}</p><button class="btn-quiet justify-self-start" type="button" @click="draft=clone(defaultState().settings)">{{ text('คืนค่าเริ่มต้นการตั้งค่า','Restore settings defaults') }}</button><p class="help">{{ text('คืนเฉพาะค่าตั้งต้น แล้วกดบันทึก กิจวัตร ประวัติ และยอดเงินยังอยู่','Restores only preferences after saving. Habits, history and money remain intact.') }}</p><p v-for="warning in state.migrationWarnings" :key="warning" class="help">{{ warning }}</p></section>
  </fieldset><ul v-if="errors.length" class="danger text-sm" role="alert"><li v-for="error in errors" :key="error">{{ error }}</li></ul><p v-if="message" class="notice text-sm" role="status">{{ message }}</p>
  <footer class="settings-footer"><span class="text-xs muted">{{ dirty?text('มีการเปลี่ยนแปลงที่ยังไม่บันทึก','You have unsaved changes'):text('การตั้งค่าตรงกับที่บันทึกแล้ว','Settings are up to date') }}</span><div class="flex gap-2"><button type="button" class="btn-quiet" :disabled="!initialized||saving" @click="load">{{ text('ยกเลิก','Cancel') }}</button><button type="submit" class="btn-primary" :disabled="!initialized||saving">{{ saving?text('กำลังบันทึก…','Saving…'):text('บันทึกการตั้งค่า','Save settings') }}</button></div></footer>
  </form>
 </div></div>
</template>
<style scoped>
.settings-layout{display:grid;gap:20px}.settings-nav{display:none}.settings-content{min-width:0;padding:24px}.theme-preview{display:flex;align-items:center;gap:16px;padding:20px;border-radius:12px;background:var(--mh-bg);color:var(--mh-ink)}.preview-light{background:#F6F5F0;color:#303D35}.preview-dark{background:#1B231F;color:#E7EDE4}.preview-dot{width:12px;height:12px;border-radius:50%;background:var(--mh-accent);flex-shrink:0}.settings-category{text-align:left;min-height:48px;border:0;padding:12px 16px;border-radius:10px;background:transparent;color:var(--mh-ink-soft)}.settings-category.active{background:var(--mh-accent-soft);color:var(--mh-accent);font-weight:600}.settings-footer{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:16px;border-top:1px solid var(--mh-line);margin-top:24px;padding-top:20px}@media(min-width:900px){.settings-layout{grid-template-columns:190px minmax(0,1fr);align-items:start}.settings-nav{display:grid;gap:4px;position:sticky;top:92px}.mobile-section{display:none}}@media(max-width:480px){.settings-content{padding:18px}.settings-footer>div{width:100%}.settings-footer>div button{flex:1}}
</style>
