<script setup lang="ts">
import type { Task } from '#shared/domain/types'
import { localDateKey, isDateKey } from '#shared/domain/dates'
import { taskDoneOn, taskAtDate } from '#shared/domain/habits'
import { resolveModule } from '#shared/domain/settings'
import { ensureDailyPlan, occurrenceId, moveTaskOccurrence, saveTaskTemplate } from '#shared/domain/daily-plan'
const {t,locale}=useI18n();const en=computed(()=>locale.value==='en');const text=(th:string,english:string)=>en.value?english:th
const {notify}=useFeedback();const {state,touch,initialized}=useWorkspace();const title=ref(''),date=ref(''),time=ref(''),schedule=ref<'once'|'daily'|'weekly'>('once'),days=ref<number[]>([])
const today=computed(()=>localDateKey(new Date(),state.value.settings.timezone));const defaults=computed(()=>resolveModule(state.value.settings,'tasks'))
watch(initialized,value=>{if(value){date.value=today.value;time.value=defaults.value.time;schedule.value=defaults.value.defaultRecurrence??'once';days.value=[...defaults.value.weekdays]}},{immediate:true})
const active=computed(()=>state.value.tasks.filter(task=>!task.archived&&!(task.status==='done'&&!task.recurrence)).sort((a,b)=>a.date.localeCompare(b.date)))
const completed=computed(()=>state.value.tasks.filter(task=>!task.archived&&task.status==='done'&&!task.recurrence))
const weekdayLabels=computed(()=>en.value?['Sun','Mon','Tue','Wed','Thu','Fri','Sat']:['อา','จ','อ','พ','พฤ','ศ','ส'])
function add(){if(!title.value.trim()||schedule.value==='weekly'&&!days.value.length)return;const task:Task={id:crypto.randomUUID(),title:title.value.trim(),date:date.value||today.value,time:time.value,priority:defaults.value.defaultPriority??'med',status:'todo',subtasks:[],createdAt:new Date().toISOString(),...(schedule.value==='once'?{}:{recurrence:schedule.value==='daily'?{type:'daily'}:{type:'weekly',weekdays:[...days.value]}})};saveTaskTemplate(state.value,task,today.value);if(!task.recurrence&&task.date===today.value&&state.value.dailyPlans[today.value]){state.value.dailyExtras[today.value]??=[];state.value.dailyExtras[today.value].push({id:occurrenceId('tasks',task.id,today.value),module:'tasks',sourceId:task.id,title:task.title,time:task.time,originDate:today.value})}title.value='';touch();notify('เพิ่มงานแล้ว','Task added')}
function archive(task:Task){ensureDailyPlan(state.value,today.value);saveTaskTemplate(state.value,{...task,archived:true},today.value);touch();notify('เก็บงานเข้าคลังแล้ว','Task archived',()=>{saveTaskTemplate(state.value,{...task,archived:false},today.value);touch()})}
function toggle(task:Task){if(taskAtDate(task,today.value).recurrence){const dates=new Set(task.completedDates??[]);if(dates.has(today.value))dates.delete(today.value);else dates.add(today.value);task.completedDates=[...dates]}else task.status=task.status==='done'?'todo':'done';touch()}
function toggleDay(task:Task,index:number){const selected=task.recurrence?.type==='weekly'?task.recurrence.weekdays:[0,1,2,3,4,5,6];saveTaskTemplate(state.value,{...task,recurrence:{type:'weekly',weekdays:selected.includes(index)?selected.filter(day=>day!==index):[...selected,index].sort()}},today.value);touch()}
function taskDate(task:Task){return state.value.dailyOverrides[task.date]?.[occurrenceId('tasks',task.id,task.date)]?.movedTo??task.date}
function move(task:Task,event:Event){const destination=(event.target as HTMLInputElement).value;if(!isDateKey(destination)||destination<today.value)return;if(task.recurrence){saveTaskTemplate(state.value,{...task,date:destination},today.value)}else moveTaskOccurrence(state.value,{id:occurrenceId('tasks',task.id,task.date),module:'tasks',sourceId:task.id,title:task.title,time:task.time,originDate:task.date},destination);touch()}
function subDone(task:Task,id:string){return taskAtDate(task,today.value).recurrence?Boolean(state.value.subtasksDone[today.value]?.[task.legacyId??task.id]?.[id]):Boolean(task.subtasks.find(sub=>sub.id===id)?.done)}
function toggleSub(task:Task,id:string,checked:boolean){if(taskAtDate(task,today.value).recurrence){state.value.subtasksDone[today.value]??={};const byTask=state.value.subtasksDone[today.value]!;byTask[task.legacyId??task.id]??={};byTask[task.legacyId??task.id]![id]=checked}else{const sub=task.subtasks.find(item=>item.id===id);if(sub)sub.done=checked}touch()}
function updateTask(task:Task,key:'title'|'time'|'priority',event:Event){const value=(event.target as HTMLInputElement).value;if(key==='title'&&!value.trim())return;ensureDailyPlan(state.value,today.value);saveTaskTemplate(state.value,{...task,[key]:value},today.value);touch()}
function repeat(task:Task,event:Event){const type=(event.target as HTMLSelectElement).value;ensureDailyPlan(state.value,today.value);saveTaskTemplate(state.value,{...task,recurrence:type==='once'?undefined:type==='daily'?{type:'daily'}:{type:'weekly',weekdays:[...defaults.value.weekdays]}},today.value);touch()}
function removeSub(task:Task,id:string){const sub=task.subtasks.find(item=>item.id===id);if(!sub)return;task.subtasks=task.subtasks.filter(item=>item.id!==id);touch();notify('ลบงานย่อยแล้ว','Subtask removed',()=>{if(!task.subtasks.some(item=>item.id===id))task.subtasks.push(sub);touch()})}
</script>
<template>
 <div class="page-wrap grid gap-5"><header><h1 class="page-title">{{ text('สิ่งที่อยากทำต่อ','Make room for what matters') }}</h1><p class="mt-2 mb-0 text-sm muted">{{ text('เลือกวัน เวลา และทำซ้ำได้ ตารางทำซ้ำที่แก้เริ่มวันถัดไป งานย่อยแยกตามรายการ','Schedule a date, time and repetition. Repeating schedule edits start tomorrow. Keep subtasks with their task.') }}</p></header>
 <form class="surface grid gap-3 p-4" @submit.prevent="add"><label class="form-label">{{ t('taskTitle') }}<input v-model="title" class="field" maxlength="160" required/></label><div class="grid gap-3 sm:grid-cols-3"><label class="form-label">{{ text('วันที่เริ่ม','Start date') }}<input v-model="date" class="field" type="date" required/></label><label class="form-label">{{ t('time') }}<input v-model="time" class="field" type="time"/></label><label class="form-label">{{ text('ทำซ้ำ','Repeat') }}<select v-model="schedule" class="field"><option value="once">{{ text('ครั้งเดียว','Once') }}</option><option value="daily">{{ text('ทุกวัน','Daily') }}</option><option value="weekly">{{ text('เลือกวัน','Selected weekdays') }}</option></select></label></div><div v-if="schedule==='weekly'" class="flex flex-wrap gap-2"><button v-for="(label,index) in weekdayLabels" :key="index" type="button" class="day-chip" :class="{chosen:days.includes(index)}" :aria-pressed="days.includes(index)" @click="days=days.includes(index)?days.filter(day=>day!==index):[...days,index]">{{ label }}</button></div><button class="btn-primary justify-self-start" type="submit" :disabled="!initialized"><UIcon name="i-lucide-plus"/>{{ t('addTask') }}</button></form>
 <section class="grid gap-3"><h2 class="m-0 text-base font-medium">{{ t('tasks') }} · {{ active.length }}</h2><p v-if="!active.length" class="surface p-6 muted text-sm">{{ t('noTasks') }}</p><article v-for="task in active" :key="task.id" class="surface p-4"><div class="flex gap-3 items-center"><label class="flex min-h-11 items-center"><input type="checkbox" class="size-5" :aria-label="`${task.title} ${t('markDone')}`" :checked="taskDoneOn(task,today)" :disabled="taskDate(task)>today" @change="toggle(task)"/></label><label class="min-w-0 flex-1"><span class="sr-only">{{ t('taskTitle') }}</span><input  :value="task.title" class="field" maxlength="160" required @change="updateTask(task,'title',$event)"/></label><button class="btn-quiet !px-3" :aria-label="text('เก็บงานเข้าคลัง','Archive task')" @click="archive(task)"><UIcon name="i-lucide-archive"/></button></div>
 <div class="grid gap-3 mt-3 sm:grid-cols-3"><label class="form-label">{{ text('วันที่','Date') }}<input class="field" type="date" :value="taskDate(task)" @change="move(task,$event)"/></label><label class="form-label">{{ t('time') }}<input  :value="task.time" class="field" type="time" @change="updateTask(task,'time',$event)"/></label><label class="form-label">{{ text('ความสำคัญ','Priority') }}<select :value="task.priority" class="field" @change="updateTask(task,'priority',$event)"><option value="low">{{ text('เบา','Low') }}</option><option value="med">{{ text('ปกติ','Normal') }}</option><option value="high">{{ text('สำคัญ','High') }}</option></select></label></div>
 <label class="form-label mt-3">{{ text('ทำซ้ำ','Repeat') }}<select class="field" :value="task.recurrence?.type??'once'" @change="repeat(task,$event)"><option value="once">{{ text('ครั้งเดียว','Once') }}</option><option value="daily">{{ text('ทุกวัน','Daily') }}</option><option value="weekly">{{ text('เลือกวัน','Selected weekdays') }}</option></select></label><div v-if="task.recurrence?.type==='weekly'" class="flex flex-wrap gap-2 mt-3"><button v-for="(label,index) in weekdayLabels" :key="index" class="day-chip" :class="{chosen:task.recurrence.weekdays.includes(index)}" :aria-pressed="task.recurrence.weekdays.includes(index)" @click="toggleDay(task,index)">{{ label }}</button></div>
 <div class="grid gap-2 mt-4"><div v-for="sub in task.subtasks" :key="sub.id" class="flex items-center gap-3"><label class="flex min-h-11 items-center"><input type="checkbox" :checked="subDone(task,sub.id)" :aria-label="sub.title||text('งานย่อย','Subtask')" @change="toggleSub(task,sub.id,($event.target as HTMLInputElement).checked)"/></label><input v-model="sub.title" class="field flex-1" maxlength="120" :aria-label="text('ชื่องานย่อย','Subtask name')" @change="touch()"/><button class="btn-quiet danger-action !px-3" :aria-label="text('ลบงานย่อย','Remove subtask')" @click="removeSub(task,sub.id)"><UIcon name="i-lucide-x" class="size-4"/></button></div><button class="btn-quiet justify-self-start text-sm" @click="task.subtasks.push({id:crypto.randomUUID(),title:'',done:false});touch()"><UIcon name="i-lucide-plus"/>{{ text('เพิ่มงานย่อย','Add subtask') }}</button></div>
 </article></section>
 <details v-if="completed.length" class="surface p-4"><summary class="min-h-11 cursor-pointer">{{ text('เสร็จแล้ว','Completed') }} · {{ completed.length }}</summary><div v-for="task in completed" :key="task.id" class="setting-row"><span>{{ task.title }}</span><button class="btn-quiet" @click="toggle(task)">{{ t('reopen') }}</button></div></details>
 <details v-if="state.tasks.some(task=>task.archived)" class="surface p-4"><summary class="min-h-11 cursor-pointer">{{ text('คลังงาน','Archived tasks') }}</summary><div v-for="task in state.tasks.filter(task=>task.archived)" :key="task.id" class="setting-row"><span>{{ task.title }}</span><button class="btn-quiet" @click="saveTaskTemplate(state,{...task,archived:false},today);touch()">{{ text('นำกลับมา','Restore') }}</button></div></details>
 </div>
</template>
