<script setup lang="ts">
import type { DailyEntry, Habit, Slot } from '#shared/domain/types'
import { dayFor, habitsForDate, passed, streak, taskAtDate } from '#shared/domain/habits'
import { entryComplete, ensureDailyPlan, planForDate, occurrenceId } from '#shared/domain/daily-plan'
import { localDateKey, dateLabel, dateOffset, isDateKey } from '#shared/domain/dates'
const {t,locale}=useI18n();const en=computed(()=>locale.value==='en');const text=(th:string,english:string)=>en.value?english:th
const {state,status,touch,initialized}=useWorkspace();const route=useRoute();const now=ref(new Date());const selected=ref(isDateKey(route.query.date)?route.query.date:'')
const currentToday=computed(()=>localDateKey(now.value,state.value.settings.timezone));const date=computed(()=>selected.value||currentToday.value)
const entries=computed(()=>planForDate(state.value,date.value));const habits=computed(()=>habitsForDate(state.value,date.value).filter(habit=>entries.value.some(entry=>entry.module==='habits'&&entry.sourceId===habit.id)))
const day=computed(()=>dayFor(state.value,date.value));const count=computed(()=>habits.value.filter(habit=>day.value.done[habit.id]&&!habitEntry(habit)?.skipped).length)
const progress=computed(()=>habits.value.length?Math.round(count.value/habits.value.length*100):0);const title=computed(()=>!habits.value.length?t('noPlan'):count.value===habits.value.length?t('allComplete'):passed(day.value)?t('dayPassed'):count.value?t('remaining',{count:Math.max(0,day.value.threshold-count.value)}):t('startSmall'))
const week=computed(()=>Array.from({length:7},(_,index)=>dateOffset(date.value,index-3)));const otherEntries=computed(()=>entries.value.filter(entry=>entry.module!=='habits'))
const groups=computed<Record<Slot,string>>(()=>({morning:t('morning'),afternoon:t('afternoon'),evening:t('evening')}));const todayStreak=computed(()=>streak(state.value,currentToday.value))
watch([initialized,currentToday],([ready,today])=>{if(ready&&ensureDailyPlan(state.value,today))touch()},{immediate:true})
watch(()=>route.query.date,value=>{selected.value=isDateKey(value)?value:''})
onMounted(()=>{const timer=window.setInterval(()=>now.value=new Date(),30_000);onBeforeUnmount(()=>window.clearInterval(timer))})
function habitEntry(habit:Habit){return entries.value.find(entry=>entry.id===occurrenceId('habits',habit.id,date.value))}
function toggle(habit:Habit,checked:boolean){const saved=state.value.habitDays[date.value]??dayFor(state.value,date.value);saved.done[habit.id]=checked;saved.updatedAt=new Date().toISOString();state.value.habitDays[date.value]=saved;touch()}
function toggleRest(){if(date.value!==currentToday.value)return;const saved=state.value.habitDays[date.value]??dayFor(state.value,date.value);saved.rest=!saved.rest;state.value.habitDays[date.value]=saved;touch()}
function toggleTask(entry:DailyEntry){const task=state.value.tasks.find(item=>item.id===entry.sourceId);if(!task)return;if(taskAtDate(task,entry.originDate).recurrence){const dates=new Set(task.completedDates??[]);if(dates.has(entry.originDate))dates.delete(entry.originDate);else dates.add(entry.originDate);task.completedDates=[...dates]}else task.status=task.status==='done'?'todo':'done';touch()}
function entryTitle(entry:DailyEntry){return entry.module==='focus'?text(`โฟกัส ${entry.target} นาที`,`Focus for ${entry.target} ${entry.target===1?'minute':'minutes'}`):entry.module==='mood'?text('แวะเช็กอารมณ์','Check in with your mood'):entry.module==='goals'?text(`บันทึก ${entry.title}`,`Check in: ${entry.title}`):entry.title}
function entryRoute(entry:DailyEntry){return entry.module==='goals'?`/goals/${entry.sourceId}?date=${entry.originDate}`:`/${entry.module}?date=${entry.originDate}`}
</script>
<template>
 <div class="page-wrap today-page">
  <header class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="page-title">{{ t('today') }}</h1><p class="mb-0 mt-2 text-sm muted">{{ dateLabel(date,locale==='th'?'th-TH':'en-US',state.settings.timezone) }}</p></div><div class="flex flex-wrap gap-2"><label class="sr-only" for="plan-date">{{ text('เลือกวันที่','Choose date') }}</label><input id="plan-date" v-model="selected" class="field !w-auto" type="date" aria-label="Plan date"/><button v-if="selected&&selected!==currentToday" class="btn-quiet" @click="selected=''">{{ t('today') }}</button><button class="btn-quiet" :disabled="!initialized||date!==currentToday" @click="toggleRest"><UIcon name="i-lucide-coffee" class="size-4"/>{{ day.rest?text('ยกเลิกวันพัก','End rest day'):text('วันนี้เป็นวันพัก','Take a rest day') }}</button></div></header>
  <div class="today-layout">
  <aside class="today-overview">
  <section class="surface today-summary grid gap-5 p-5 sm:p-7">
   <div class="flex items-center gap-5"><div v-if="habits.length" class="relative grid size-[100px] shrink-0 place-items-center"><svg viewBox="0 0 112 112" class="size-full -rotate-90" aria-hidden="true"><circle cx="56" cy="56" r="47" fill="none" stroke="var(--mh-line)" stroke-width="7"/><circle cx="56" cy="56" r="47" fill="none" :stroke="passed(day)?'var(--mh-success)':'var(--mh-accent)'" stroke-width="7" stroke-linecap="round" stroke-dasharray="295.31" :stroke-dashoffset="295.31*(1-progress/100)"/></svg><strong class="absolute mono text-2xl">{{ count }}<span class="text-sm muted">/{{ habits.length }}</span></strong></div><div><h2 class="m-0 text-lg font-semibold sm:text-2xl">{{ title }}</h2><p class="mt-2 mb-0 text-sm muted">{{ day.rest?text('พักได้เต็มที่ วันนี้นับเป็นวันดูแลตัวเอง','Rest is part of taking care of yourself.'):habits.length?text(`${day.threshold} จาก ${habits.length} กิจวัตรเพื่อให้วันนี้ผ่าน`,`${day.threshold} of ${habits.length} habits to pass today`):text('เพิ่มรายการหรือเลือกโมดูลสำหรับวันนี้','Add items or choose daily modules') }}</p><p v-if="habits.length" class="mt-2 mb-0 text-xs success">{{ t('bestStreak') }} · {{ todayStreak }} {{ text('วัน','days') }}</p></div></div>
   <div class="week-strip border-t pt-4" style="border-color:var(--mh-line)"><button v-for="key in week" :key="key" class="day-button" :class="{selected:date===key}" :aria-pressed="date===key" @click="selected=key"><span>{{ new Intl.DateTimeFormat(en?'en-US':'th-TH',{weekday:'short',timeZone:'UTC'}).format(new Date(`${key}T12:00:00Z`)) }}</span><span class="mono">{{ Number(key.slice(-2)) }}</span></button></div>
  </section>
  <div class="overview-links"><NuxtLink to="/progress"><UIcon name="i-lucide-chart-no-axes-column-increasing" class="size-5"/><span>{{ text('มองย้อนดูความคืบหน้า','See your progress') }}</span><UIcon name="i-lucide-arrow-right" class="size-4"/></NuxtLink><NuxtLink to="/settings?section=daily"><UIcon name="i-lucide-sliders-horizontal" class="size-5"/><span>{{ text('เลือกโมดูลในวันนี้','Choose daily modules') }}</span><UIcon name="i-lucide-arrow-right" class="size-4"/></NuxtLink></div>
  </aside>
  <div class="daily-agenda">
  <div class="agenda-heading"><h2>{{ text('กิจวัตรของคุณ','Your daily routine') }}</h2><span>{{ text(`${count} / ${habits.length} เสร็จแล้ว`,`${count} / ${habits.length} complete`) }}</span></div>
  <section v-for="slot in (['morning','afternoon','evening'] as Slot[])" v-show="habits.some(habit=>habit.slot===slot)" :key="slot" class="habit-group"><h3 class="period-heading"><UIcon :name="slot==='morning'?'i-lucide-sunrise':slot==='evening'?'i-lucide-moon':'i-lucide-sun'" class="size-4"/>{{ groups[slot] }}<span>{{ habits.filter(habit=>habit.slot===slot).length }}</span></h3><div class="surface overflow-hidden"><label v-for="habit in habits.filter(item=>item.slot===slot)" :key="habit.id" class="habit-row" :class="{'is-done':day.done[habit.id],'is-skipped':habitEntry(habit)?.skipped}"><input class="peer sr-only" type="checkbox" :checked="Boolean(day.done[habit.id])" :disabled="!initialized||date>currentToday||habitEntry(habit)?.skipped" @change="toggle(habit,($event.target as HTMLInputElement).checked)"/><span class="check-indicator"><UIcon v-if="day.done[habit.id] && !habitEntry(habit)?.skipped" name="i-lucide-check" class="size-4"/></span><span class="min-w-0 flex-1"><strong class="block text-base font-medium">{{ habit.title }}</strong><small class="block text-sm muted">{{ habitEntry(habit)?.skipped?text('ข้ามเฉพาะวันนี้','Skipped for this day'):habit.description }}</small></span><span class="habit-time mono muted">{{ habitEntry(habit)?.time??habit.time }}</span></label></div></section>
  <div v-if="!habits.length" class="empty-agenda"><UIcon name="i-lucide-leaf" class="size-8 success"/><h3>{{ text('เว้นที่ให้สิ่งเล็ก ๆ ที่อยากทำ','Make room for a small habit') }}</h3><p class="muted">{{ text('เลือกกิจวัตรประจำ หรือเพิ่มรายการเฉพาะวันด้านล่าง','Choose a daily habit or add an item for this day below') }}</p><NuxtLink to="/settings?section=modules&module=habits" class="btn-primary">{{ text('เลือกกิจวัตร','Choose habits') }}</NuxtLink></div>
  <section v-if="otherEntries.length" class="grid gap-2"><h2 class="m-0 text-sm font-medium muted">{{ text('งานและเช็กอินวันนี้','Tasks & check-ins') }}</h2><div class="surface overflow-hidden"><div v-for="entry in otherEntries" :key="entry.id" class="checkin-row"><label v-if="entry.module==='tasks'" class="flex min-h-11 flex-1 items-center gap-3"><input type="checkbox" :checked="entryComplete(state,entry)" :disabled="!initialized||date>currentToday||entry.skipped" :aria-label="entry.title" @change="toggleTask(entry)"/><span class="text-sm" :class="{'line-through muted':entryComplete(state,entry)}">{{ entryTitle(entry) }}</span></label><span v-else class="flex-1 text-sm">{{ entryTitle(entry) }}</span><span v-if="entry.skipped" class="text-xs muted">{{ text('ข้ามวันนี้','Skipped') }}</span><span v-else-if="entryComplete(state,entry)" class="text-xs success">{{ text('เสร็จแล้ว','Done') }}</span><NuxtLink v-else-if="entry.module!=='tasks'" :to="entryRoute(entry)" class="btn-quiet text-xs">{{ text('เปิด','Open') }}<UIcon name="i-lucide-arrow-up-right" class="size-4"/></NuxtLink><span v-if="entry.time" class="text-xs mono muted">{{ entry.time }}</span></div></div></section>
  <DailyPlanEditor :date="date"/>
  <div class="flex flex-wrap gap-3 text-sm"><NuxtLink to="/settings?section=modules&module=habits" class="settings-link"><UIcon name="i-lucide-settings-2"/>{{ text('ตั้งค่ากิจวัตรประจำ','Habit settings') }}</NuxtLink><NuxtLink to="/settings?section=daily" class="settings-link">{{ text('เลือกโมดูลในวันนี้','Choose daily modules') }}</NuxtLink></div>
  <p v-if="status==='loading'" class="m-0 text-center text-xs muted" role="status">{{ text('กำลังโหลดข้อมูล…','Loading your data…') }}</p><p v-else-if="status==='offline'" class="m-0 text-center text-xs muted" role="status">{{ t('offline') }}</p>
  </div></div>
 </div>
</template>
<style scoped>
.week-strip{display:grid;grid-template-columns:repeat(7,minmax(44px,1fr));gap:4px;overflow-x:auto}.day-button{display:grid;justify-items:center;gap:3px;min-height:56px;padding:6px 2px;border:0;border-radius:10px;background:transparent;color:var(--mh-muted);font-size:.75rem}.day-button.selected{background:var(--mh-accent-soft);color:var(--mh-accent);font-weight:600}.habit-row{display:flex;min-height:76px;align-items:center;gap:12px;padding:14px 16px;cursor:pointer}.habit-row+.habit-row,.checkin-row+.checkin-row{border-top:1px solid var(--mh-line)}.habit-icon{display:grid;place-items:center;width:40px;height:40px;flex-shrink:0;color:var(--mh-ink-soft)}.check-indicator{display:grid;place-items:center;width:28px;height:28px;border:1px solid var(--mh-line);border-radius:50%;flex-shrink:0}.is-done .check-indicator{background:var(--mh-success-soft);border-color:var(--mh-success);color:var(--mh-success)}.is-done strong{color:var(--mh-muted)}.is-skipped{opacity:.7}.habit-row:has(input:focus-visible){outline:2px solid var(--mh-accent);outline-offset:-3px}.checkin-row{display:flex;flex-wrap:wrap;gap:12px;align-items:center;padding:12px 16px}.checkin-row input{width:18px;height:18px}@media(max-width:420px){.habit-row{padding:12px;gap:8px}.habit-icon{width:28px}.habit-row .mono{font-size:.65rem}}
</style>
<style scoped>
.today-page{display:grid;gap:32px}.today-layout{display:grid;gap:28px;align-items:start}.today-overview{display:grid;gap:16px;min-width:0}.daily-agenda{display:grid;gap:24px;min-width:0}.today-summary{background:var(--mh-success-soft)}.today-summary>.flex{align-items:flex-start}.agenda-heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.agenda-heading h2{margin:0;font-size:1.25rem;font-weight:600}.agenda-heading>span{font-size:.8rem;color:var(--mh-muted)}.habit-group{display:grid;gap:10px}.period-heading{display:flex;align-items:center;gap:8px;margin:0;color:var(--mh-ink-soft);font-size:.875rem;font-weight:500}.period-heading>span:not(.iconify){margin-left:auto;font-size:.75rem;color:var(--mh-muted)}.habit-row{min-height:86px;padding:18px 20px;gap:16px;transition:background 160ms ease}.habit-row:hover{background:var(--mh-hover)}.is-done{background:var(--mh-success-soft)}.is-done strong{color:var(--mh-success)}.check-indicator{width:26px;height:26px;border-radius:8px;border-color:var(--mh-control-line)}.is-done .check-indicator{background:var(--mh-success);color:var(--mh-accent-ink)}.habit-time{font-size:.75rem;white-space:nowrap}.overview-links{display:grid}.overview-links a{display:flex;align-items:center;gap:10px;min-height:52px;padding:12px 4px;border-bottom:1px solid var(--mh-line);text-decoration:none;color:var(--mh-ink-soft);font-size:.875rem}.overview-links a>span:not(.iconify){flex:1}.overview-links a:hover{color:var(--mh-accent)}.empty-agenda{padding:24px 0}.empty-agenda h3{font-size:1.1rem}.week-strip{grid-template-columns:repeat(7,minmax(0,1fr));gap:2px}.day-button{min-height:58px;min-width:0}.day-button:hover{background:var(--mh-hover)}.day-button.selected{background:var(--mh-accent);color:var(--mh-accent-ink)}
@media(min-width:1200px){.today-layout{grid-template-columns:320px minmax(0,1fr);gap:36px}.today-overview{position:sticky;top:108px}.today-summary>.flex{flex-direction:column;gap:20px}.today-summary .week-strip{margin-inline:-12px}}
@media(max-width:480px){.today-page{gap:24px}.today-page>header>div:last-child{width:100%}.today-page>header .field{flex:1;max-width:100%}.habit-row{padding:16px 12px;gap:12px}.habit-time{font-size:.7rem}.today-summary{padding:20px}.today-summary>.flex{gap:14px}.today-summary .size-\[100px\]{width:80px;height:80px}.overview-links{display:none}}
</style>
