<script setup lang="ts">
import { exchangeAmount } from '#shared/domain/exchange'
import { resolveModule } from '#shared/domain/settings'
import { convert, healthEstimate, unitSets, type ConverterKind } from '#shared/domain/converters'
const {state,initialized}=useWorkspace();const route=useRoute();const {t,locale}=useI18n()
const text=(th:string,english:string)=>locale.value==='en'?english:th
const allowed:ConverterKind[]=['length','weight','volume','temperature','time','speed','fuel','currency','bmi','bmr','tdee']
const kind=computed(()=>allowed.includes(String(route.params.kind) as ConverterKind)?String(route.params.kind) as ConverterKind:'length')
const labelMap=computed<Record<ConverterKind,string>>(()=>({length:text('ระยะทาง','Length'),weight:text('น้ำหนัก','Weight'),volume:text('ปริมาตร','Volume'),temperature:text('อุณหภูมิ','Temperature'),time:text('เวลา','Time'),speed:text('ความเร็ว','Speed'),fuel:text('อัตราสิ้นเปลือง','Fuel economy'),currency:text('สกุลเงิน','Currency'),bmi:text('ดัชนีมวลกาย','Body mass index'),bmr:text('พลังงานพื้นฐาน','Basal metabolic rate'),tdee:text('พลังงานต่อวัน','Daily energy needs')}))
const units=computed(()=>kind.value in unitSets?unitSets[kind.value as keyof typeof unitSets]:[])
const value=ref(1);const from=ref('kg');const to=ref('lb');const error=ref('');const result=ref<number|null>(null)
const { snapshot, loading, cached, failed, refresh } = useExchangeRates()
watch(kind, value => { if(value==='currency' && import.meta.client) void refresh() }, { immediate:true })
function swap(){const previous=from.value;from.value=to.value;to.value=previous}
const height=ref(170);const weight=ref(70);const age=ref(30);const sex=ref<'female'|'male'>('female');const activity=ref(1.2)
watch([kind,initialized],([value])=>{const pair=resolveModule(state.value.settings,'tools').unitPairs?.[value];from.value=pair?.from??unitSets[value as keyof typeof unitSets]?.[0]?.id??'';to.value=pair?.to??unitSets[value as keyof typeof unitSets]?.[1]?.id??'';result.value=null;error.value=''},{immediate:true})
watch([value,from,to,height,weight,age,sex,activity,snapshot],()=>{result.value=null;error.value=''})
function run(){try{error.value='';if(!Number.isFinite(Number(value.value)))throw new Error(text('กรอกตัวเลขให้ถูกต้อง','Enter a valid number'));if(kind.value==='currency'){if(from.value===to.value){result.value=Number(value.value);return}if(!snapshot.value){error.value=text('ยังโหลดอัตราไม่ได้ กดโหลดใหม่แล้วลองอีกครั้ง','Rates are unavailable. Refresh rates and try again.');return}result.value=exchangeAmount(Number(value.value),from.value,to.value,snapshot.value);return}result.value=['bmi','bmr','tdee'].includes(kind.value)?healthEstimate(kind.value as 'bmi'|'bmr'|'tdee',{heightCm:height.value,weightKg:weight.value,age:age.value,sex:sex.value,activity:activity.value}):convert(Number(value.value),kind.value,from.value,to.value)}catch(reason){result.value=null;error.value=reason instanceof Error?reason.message:'แปลงค่าไม่สำเร็จ'}}
</script>
<template>
  <div class="page-wrap mx-auto grid max-w-2xl gap-5"><header><NuxtLink to="/tools" class="text-sm accent no-underline">← {{ t('tools') }}</NuxtLink><h1 class="page-title">{{ labelMap[kind] }}</h1></header><form class="surface grid gap-4 p-5" @submit.prevent="run">
    <template v-if="['bmi','bmr','tdee'].includes(kind)"><label class="grid gap-1 text-sm">{{ text('ส่วนสูง (ซม.)','Height (cm)') }}<input v-model.number="height" class="field" type="number" min="1" max="300" step="any" required/></label><label class="grid gap-1 text-sm">{{ text('น้ำหนัก (กก.)','Weight (kg)') }}<input v-model.number="weight" class="field" type="number" min="1" max="700" step="any" required/></label><label class="grid gap-1 text-sm">{{ text('อายุ','Age') }}<input v-model.number="age" class="field" type="number" min="1" max="120" required/></label><label class="grid gap-1 text-sm">{{ text('สูตรที่ใช้','Formula') }}<select v-model="sex" class="field"><option value="female">{{ text('หญิง','Female') }}</option><option value="male">{{ text('ชาย','Male') }}</option></select></label><label v-if="kind==='tdee'" class="grid gap-1 text-sm">{{ text('กิจกรรม','Activity') }}<select v-model.number="activity" class="field"><option :value="1.2">{{ text('นั่งเป็นส่วนใหญ่ · 1.2','Mostly sitting · 1.2') }}</option><option :value="1.375">{{ text('ออกกำลังเบา · 1.375','Light activity · 1.375') }}</option><option :value="1.55">{{ text('ออกกำลังปานกลาง · 1.55','Moderate activity · 1.55') }}</option><option :value="1.725">{{ text('ออกกำลังหนัก · 1.725','Heavy activity · 1.725') }}</option><option :value="1.9">{{ text('กิจกรรมหนักมาก · 1.9','Very heavy activity · 1.9') }}</option></select></label></template>
    <template v-else><label class="grid gap-1 text-sm">{{ text('จำนวน','Amount') }}<input v-model.number="value" class="field" type="number" step="any" required/></label><div class="grid grid-cols-[1fr_auto_1fr] items-end gap-3"><label class="grid gap-1 text-sm">{{ t('from') }}<select v-model="from" class="field"><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ locale==='en'?unit.id:unit.label }}</option></select></label><button type="button" class="btn-quiet !px-3" :aria-label="text('สลับหน่วย','Swap units')" @click="swap"><UIcon name="i-lucide-arrow-left-right" class="size-4"/></button><label class="grid gap-1 text-sm">{{ t('to') }}<select v-model="to" class="field"><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ locale==='en'?unit.id:unit.label }}</option></select></label></div><div v-if="kind==='currency'" class="rate-status" :aria-busy="loading"><p v-if="snapshot" class="m-0 text-sm muted">{{ text('อัตราอ้างอิง ณ วันที่','Reference rates dated') }} {{ snapshot.date }} · <a href="https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html" target="_blank" rel="noopener noreferrer" class="accent">ECB</a> / <a href="https://frankfurter.dev/" target="_blank" rel="noopener noreferrer" class="accent">Frankfurter</a></p><p v-if="cached&&failed" class="m-0 text-sm" style="color:var(--mh-warning)" role="status">{{ text('ใช้ข้อมูลที่เก็บไว้ โหลดข้อมูลล่าสุดไม่สำเร็จ ตรวจวันที่ก่อนใช้','Using saved rates; the latest request failed. Check the date before using.') }}</p><p v-else-if="failed" class="m-0 text-sm danger" role="alert">{{ text('โหลดอัตราไม่สำเร็จ ตรวจอินเทอร์เน็ตแล้วลองใหม่','Rates could not load. Check your connection and retry.') }}</p><button type="button" class="btn-quiet justify-self-start text-sm" :disabled="loading" @click="refresh"><UIcon name="i-lucide-refresh-cw" class="size-4" :class="{'loading-spin':loading}"/>{{ loading?text('กำลังโหลดอัตรา…','Loading rates…'):text('โหลดอัตราใหม่','Refresh rates') }}</button><p class="m-0 text-xs muted">{{ text('อัตราอ้างอิงรายวัน ไม่รวมค่าธรรมเนียมหรือส่วนต่างของผู้ให้บริการ','Daily reference rates, excluding provider fees and spreads.') }}</p></div></template>
    <button class="btn-primary justify-self-start" :disabled="!initialized || kind==='currency' && from!==to && !snapshot">{{ text('แปลงค่า','Convert') }} <UIcon name="i-lucide-arrow-right"/></button>
    <p v-if="result!==null" role="status" class="conversion-result m-0 rounded-2xl p-4 text-2xl font-bold mono" style="background:var(--mh-accent-soft);color:var(--mh-accent)">{{ result.toLocaleString(locale==='th'?'th-TH':'en-US',{maximumFractionDigits:kind==='currency'?(to==='JPY'?0:2):4}) }}<small v-if="kind==='currency'" class="ml-2 text-sm">{{ to }}</small><small v-if="['bmr','tdee'].includes(kind)" class="ml-2 text-xs font-medium">{{ text('kcal/วันโดยประมาณ','estimated kcal/day') }}</small></p><p v-if="error" class="m-0 text-sm danger" role="alert">{{ error }}</p>
  </form><p v-if="['bmi','bmr','tdee'].includes(kind)" class="m-0 text-xs muted">{{ text('เป็นการประมาณจากสูตรทั่วไป ใช้ทำความเข้าใจเบื้องต้น ไม่ใช่คำวินิจฉัยหรือคำแนะนำทางการแพทย์','An estimate based on general formulas, for basic understanding; this is not a medical diagnosis or advice') }}</p></div>
</template>

<style scoped>.rate-status{display:grid;gap:12px;padding-top:16px;border-top:1px solid var(--mh-line)}.conversion-result{animation:result-confirm 220ms var(--ease-out)}</style>
