<script setup lang="ts">
import type { FinanceEntry, GoalEntry } from '#shared/domain/types'
import { localDateKey, isDateKey } from '#shared/domain/dates'
const route=useRoute();const {t,locale}=useI18n();const {state,touch,initialized}=useWorkspace();const value=ref('');const note=ref('')
const {notify}=useFeedback();const editingId=ref('');const configTitle=ref(''),configTarget=ref(0),configStarting=ref(0);const configError=ref('')
const today=computed(()=>localDateKey(new Date(),state.value.settings.timezone));const recordDate=computed(()=>isDateKey(route.query.date)&&route.query.date<=today.value?route.query.date:today.value)
const goal=computed(()=>state.value.goals.find(item=>item.id===route.params.id))
const records=computed(()=>goal.value?.kind==='financial'?state.value.financeEntries.filter(item=>item.goalId===goal.value?.id).map(item=>({id:item.id,date:item.date,value:item.amountMinor/100,note:item.note||item.category,kind:item.kind,unit:item.currency})).sort((a,b)=>b.date.localeCompare(a.date)):state.value.goalEntries.filter(item=>item.goalId===route.params.id).sort((a,b)=>b.date.localeCompare(a.date)).map(item=>({...item,kind:'weight',unit:goal.value?.unit??'kg'})))
function save(){const n=Number(value.value);if(!initialized.value||!goal.value||!Number.isFinite(n)||n<=0||goal.value.kind==='financial'&&(!Number.isSafeInteger(Math.round(n*100))||Math.round(n*100)<1))return;const editing=editingId.value;const date=recordDate.value;if(goal.value.kind==='financial'){const entry:FinanceEntry={id:crypto.randomUUID(),goalId:goal.value.id,date,kind:editing?(state.value.financeEntries.find(row=>row.id===editing)?.kind??'income'):'income',amountMinor:Math.round(n*100),currency:goal.value.unit,category:'เพิ่มเงินเข้าเป้าหมาย',note:note.value.trim()||undefined,sourceKey:`goal-contribution:${crypto.randomUUID()}`};if(editing){const index=state.value.financeEntries.findIndex(row=>row.id===editing);if(index>=0){entry.id=editing;entry.sourceKey=state.value.financeEntries[index]?.sourceKey;entry.category=state.value.financeEntries[index]?.category;entry.currency=state.value.financeEntries[index]?.currency??goal.value.unit;state.value.financeEntries.splice(index,1,entry)}}else state.value.financeEntries.push(entry)}else{const entry:GoalEntry={id:crypto.randomUUID(),goalId:goal.value.id,date,value:n,note:note.value.trim()||undefined};if(editing){const index=state.value.goalEntries.findIndex(row=>row.id===editing);if(index>=0){entry.id=editing;state.value.goalEntries.splice(index,1,entry)}}else state.value.goalEntries.push(entry)}value.value='';note.value='';editingId.value='';touch();notify(editing?'อัปเดตบันทึกแล้ว':'บันทึกความคืบหน้าแล้ว',editing?'Entry updated':'Progress saved')}
const text=(th:string,english:string)=>locale.value==='en'?english:th
watch(goal,item=>{if(item){configTitle.value=item.title;configTarget.value=item.target;configStarting.value=item.startingValue}},{immediate:true})
function saveConfig(){if(!goal.value||!configTitle.value.trim()||!Number.isFinite(configTarget.value)||configTarget.value<=0||!Number.isFinite(configStarting.value)||configStarting.value<0||goal.value.kind==='weight'&&configStarting.value<=0){configError.value=text('กรอกชื่อ เป้าหมาย และค่าเริ่มต้นให้ถูกต้อง','Enter a valid name, target and starting value');return}Object.assign(goal.value,{title:configTitle.value.trim(),target:configTarget.value,startingValue:configStarting.value});configError.value='';touch();notify('อัปเดตเป้าหมายแล้ว','Goal updated')}
function editRecord(row:{id:string;date:string;value:number;note?:string}){editingId.value=row.id;value.value=String(row.value);note.value=row.note??'';void navigateTo({query:{date:row.date}})}
function removeRecord(id:string){const financial=goal.value?.kind==='financial';const rows=financial?state.value.financeEntries:state.value.goalEntries;const entry=rows.find(row=>row.id===id);if(!entry)return;if(financial)state.value.financeEntries=state.value.financeEntries.filter(row=>row.id!==id);else state.value.goalEntries=state.value.goalEntries.filter(row=>row.id!==id);if(editingId.value===id){editingId.value='';value.value='';note.value=''}touch();notify('ลบบันทึกแล้ว','Entry removed',()=>{if(financial){if(!state.value.financeEntries.some(row=>row.id===id))state.value.financeEntries.push(entry as FinanceEntry)}else if(!state.value.goalEntries.some(row=>row.id===id))state.value.goalEntries.push(entry as GoalEntry);touch()})}
</script>
<template>
  <div v-if="goal" class="page-wrap grid max-w-3xl gap-5">
    <header><NuxtLink to="/goals" class="text-sm accent no-underline">← {{ t('goals') }}</NuxtLink><h1 class="page-title">{{ goal.title }}</h1><p class="mb-0 mt-2 text-sm muted">{{ t('goals') }} {{ goal.target.toLocaleString() }} {{ goal.unit }}</p></header>
    <p class="m-0 text-sm muted">{{ recordDate }}</p><form class="surface grid gap-3 p-4 sm:grid-cols-[180px_1fr_auto] sm:items-end" @submit.prevent="save"><label class="grid gap-1 text-xs muted"><span>{{ goal.kind==='financial'?text('ยอดเงินที่เพิ่ม','Contribution amount'):t('logValue') }} · {{ goal.unit }}</span><input v-model="value" class="field" type="number" min="0.01" step="any" required/></label><label class="grid gap-1 text-xs muted"><span>{{ t('note') }}</span><input v-model="note" class="field" maxlength="160"/></label><div class="flex gap-2"><button v-if="editingId" type="button" class="btn-quiet" @click="editingId='';value='';note=''">{{ t('cancel') }}</button><button class="btn-primary" :disabled="!initialized">{{ editingId?t('save'):t('addRecord') }}</button></div></form>
    <section class="surface p-4"><h2 class="m-0 text-base font-bold">{{ text('ประวัติ','History') }}</h2><p v-if="!records.length" class="mb-0 mt-3 text-sm muted">{{ text('ยังไม่มีรายการบันทึก','No entries yet') }}</p><div v-for="row in records" :key="row.id" class="flex justify-between gap-3 border-t py-3 text-sm" style="border-color:var(--mh-line)"><span>{{ row.note||goal.title }} <small class="block muted">{{ row.date }} · {{ row.kind==='income'?text('เพิ่มเข้าเป้าหมาย','Goal contribution'):'' }}</small></span><div class="flex flex-wrap items-center gap-2"><span class="mono font-semibold">{{ (row.kind==='expense'?-row.value:row.value).toLocaleString() }} {{ row.unit }}</span><button class="btn-quiet !px-3" :aria-label="text('แก้ไขบันทึก','Edit record')" @click="editRecord(row)"><UIcon name="i-lucide-pencil" class="size-4"/></button><button class="btn-quiet danger-action !px-3" :aria-label="text('ลบบันทึก','Remove record')" @click="removeRecord(row.id)"><UIcon name="i-lucide-x" class="size-4"/></button></div></div></section>
    <details class="surface p-5"><summary class="min-h-11 cursor-pointer">{{ text('แก้ไขเป้าหมาย','Edit goal') }}</summary><form class="mt-4 grid gap-4" @submit.prevent="saveConfig"><label class="form-label">{{ t('goalTitle') }}<input v-model="configTitle" class="field" maxlength="100" required/></label><div class="grid gap-4 sm:grid-cols-2"><label class="form-label">{{ t('target') }}<input v-model.number="configTarget" class="field" type="number" min="0.01" step="any" required/></label><label class="form-label">{{ text('ค่าเริ่มต้น','Starting value') }}<input v-model.number="configStarting" class="field" type="number" :min="goal.kind==='weight'?0.01:0" step="any" required/></label></div><p v-if="configError" class="danger text-sm" role="alert">{{ configError }}</p><button class="btn-primary justify-self-start" :disabled="!initialized">{{ t('save') }}</button></form></details>
  </div>
  <div v-else class="page-wrap"><NuxtLink to="/goals" class="accent">{{ text('กลับไปเป้าหมาย','Back to goals') }}</NuxtLink></div>
</template>
