<script setup lang="ts">
import { resolveModule } from '#shared/domain/settings'
import QRCode from 'qrcode'
import type { BillDraft } from '#shared/domain/types'
import { promptPayPayload } from '#shared/domain/promptpay'
import { splitBill } from '#shared/domain/split-bill'
const {t,locale}=useI18n();const {state,touch,initialized}=useWorkspace()
const {notify}=useFeedback();let qrRevision=0;const qrError=ref('')
const defaults=computed(()=>resolveModule(state.value.settings,'tools'));const rates=ref({service:.1,vat:.07});const defaultsLoaded=ref(false)
const amount=ref('');const peopleCount=ref(2);const service=ref(false);const vat=ref(false);const identifier=ref('');const idType=ref<'phone'|'national-id'>('phone');const names=ref<string[]>(['','']);const shares=ref<number[]>([1,1]);const result=ref<ReturnType<typeof splitBill>|null>(null);const qrImages=ref<Record<string,string>>({});const error=ref('');const busy=ref(false);const saved=ref(false)
watch(peopleCount,(count)=>{names.value=Array.from({length:count},(_,i)=>names.value[i]??'');shares.value=Array.from({length:count},(_,i)=>shares.value[i]??1);calculate()})
watch(shares,calculate,{deep:true})
watch(names,calculate,{deep:true})
watch([amount,service,vat],calculate)
function calculate(){saved.value=false;if(!amount.value){result.value=null;qrImages.value={};qrRevision++;return}try{error.value='';const amountMinor=Math.round(Number(amount.value)*100);const next=splitBill({amountMinor,people:names.value.map((name,index)=>({id:String(index+1),name:name.trim(),share:shares.value[index]??1})),serviceRate:service.value ? rates.value.service : 0,vatRate:vat.value ? rates.value.vat : 0});result.value=next;void makeQr()}catch(reason){result.value=null;qrImages.value={};qrRevision++;error.value=reason instanceof Error?reason.message:'ตรวจสอบยอดอีกครั้ง'}}
async function makeQr(){qrError.value='';const generation=++qrRevision;const current=result.value;const receiver=identifier.value.trim(),type=idType.value;if(!current||!receiver){qrImages.value={};busy.value=false;return}qrImages.value={};busy.value=true;const images:Record<string,string>={};try{for(const person of current.people){const payload=promptPayPayload(receiver,type,person.amountMinor);images[person.id]=await QRCode.toDataURL(payload,{errorCorrectionLevel:'M',margin:2,width:240,color:{dark:'#000000',light:'#ffffff'}})}if(generation===qrRevision)qrImages.value=images}catch(reason){if(generation===qrRevision){qrError.value=reason instanceof Error?reason.message:'สร้าง QR ไม่สำเร็จ';qrImages.value={}}}finally{if(generation===qrRevision)busy.value=false}}

watch([identifier,idType],()=>void makeQr())
function saveDraft(){if(!result.value)return;const draft:BillDraft={id:crypto.randomUUID(),title:`${locale.value==='th'?'บิล':'Bill'} ${new Date().toLocaleDateString(locale.value==='th'?'th-TH':'en-US')}`,amountMinor:result.value.amountMinor,serviceRate:service.value ? rates.value.service : 0,vatRate:vat.value ? rates.value.vat : 0,createdAt:new Date().toISOString(),people:result.value.people.map(person=>({id:person.id,name:person.name,amountMinor:person.amountMinor,share:person.share??1}))};state.value.billDrafts.push(draft);touch();saved.value=true;notify('บันทึกบิลในอุปกรณ์แล้ว','Bill saved on this device')}
function restoreDraft(draft:BillDraft){amount.value=(draft.amountMinor/100).toFixed(2);peopleCount.value=Math.max(1,draft.people.length);names.value=draft.people.map(person=>person.name);shares.value=draft.people.map(person=>person.share??1);service.value=draft.serviceRate>0;vat.value=draft.vatRate>0;rates.value={service:draft.serviceRate||defaults.value.serviceRate||.1,vat:draft.vatRate||defaults.value.vatRate||.07};calculate();saved.value=false}
function removeDraft(draft:BillDraft){state.value.billDrafts=state.value.billDrafts.filter(row=>row.id!==draft.id);touch();notify('ลบบิลแล้ว','Bill removed',()=>{if(!state.value.billDrafts.some(row=>row.id===draft.id))state.value.billDrafts.push(draft);touch()})}
function download(image:string,name:string){const link=document.createElement('a');link.href=image;link.download=`myhabit-promptpay-${name||'qr'}.png`;link.click()}
async function copyAmounts(){if(!result.value)return;try{await navigator.clipboard.writeText(result.value.people.map(person=>`${person.name||`คนที่ ${person.id}`}: ${currency(person.amountMinor)}`).join('\n'));notify('คัดลอกยอดแล้ว','Amounts copied')}catch{error.value='คัดลอกไม่ได้ · เลือกข้อความและคัดลอกด้วยตนเอง'}}
watch([initialized,()=>state.value.settings],()=>{if(initialized.value&&!defaultsLoaded.value){const config=defaults.value;peopleCount.value=config.peopleCount??2;service.value=config.serviceEnabled??false;vat.value=config.vatEnabled??false;rates.value={service:config.serviceRate??.1,vat:config.vatRate??.07};defaultsLoaded.value=true;const draft=state.value.billDrafts.at(-1);if(draft)restoreDraft(draft)}},{immediate:true})

const currency=(minor:number)=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(minor/100)
const text=(th:string,english:string)=>locale.value==='en'?english:th
</script>
<template>
  <div class="page-wrap grid gap-5"><header><NuxtLink to="/tools" class="text-sm accent no-underline">← {{ t('tools') }}</NuxtLink><h1 class="page-title">{{ text('หารกันพอดีทุกสตางค์','Split every satang fairly') }}</h1><p class="mb-0 mt-1 text-sm muted">{{ text('คำนวณในอุปกรณ์นี้ หมายเลขพร้อมเพย์ไม่ถูกส่งไปสร้างรูป QR ภายนอก','Calculated on this device; PromptPay QR images are generated locally') }}</p></header>
    <form class="surface p-4 sm:p-5" @submit.prevent="calculate"><fieldset :disabled="!defaultsLoaded" class="m-0 grid min-w-0 gap-4 border-0 p-0"><label class="grid gap-1 text-sm font-semibold">{{ t('amount') }} · THB<input v-model="amount" class="field mono" type="number" min="0.01" max="99999999" step="0.01" required inputmode="decimal"/></label><label class="grid gap-1 text-sm font-semibold">{{ t('people') }}<select v-model.number="peopleCount" class="field"><option v-for="n in 30" :key="n" :value="n">{{ n }} คน</option></select></label><div class="grid grid-cols-2 gap-2"><label class="flex min-h-12 items-center gap-2 rounded-xl border px-3 text-sm" style="border-color:var(--mh-line)"><input v-model="service" type="checkbox" class="size-4 accent-[var(--mh-accent)]"/>{{ locale==='th'?'ค่าบริการ':'Service charge' }} {{ Math.round(rates.service*10000)/100 }}%</label><label class="flex min-h-12 items-center gap-2 rounded-xl border px-3 text-sm" style="border-color:var(--mh-line)"><input v-model="vat" type="checkbox" class="size-4 accent-[var(--mh-accent)]"/>VAT {{ Math.round(rates.vat*10000)/100 }}%</label></div>
      <details class="rounded-2xl border p-3" style="border-color:var(--mh-line)"><summary class="min-h-11 cursor-pointer text-sm font-semibold">{{ text('ใส่ชื่อคนและปรับสัดส่วนหาร','Names and share weights') }}</summary><div class="mt-3 grid gap-2"> <div v-for="(_,index) in names" :key="index" class="grid grid-cols-[1fr_110px] gap-2"><input v-model="names[index]" class="field" maxlength="50" :placeholder="`คนที่ ${index+1}`"/><input v-model.number="shares[index]" class="field text-center" type="number" min="1" max="10000" step="1" :aria-label="`สัดส่วนคนที่ ${index+1}`"/></div></div><p class="mb-0 mt-2 text-xs muted">{{ text('ตัวเลขเป็นสัดส่วนเทียบกัน เช่น 2 ต่อ 1 จะแบ่งยอดให้คนแรกมากเป็นสองเท่า','Weights are proportional: 2 to 1 gives the first person twice the share') }}</p></details>
      <details class="rounded-2xl border p-3" style="border-color:var(--mh-line)"><summary class="min-h-11 cursor-pointer text-sm font-semibold">{{ text('สร้าง QR PromptPay ในเครื่อง (ไม่บังคับ)','Generate a local PromptPay QR (optional)') }}</summary><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="grid gap-1 text-xs muted"><span>{{ text('ชนิดเลขพร้อมเพย์','PromptPay ID type') }}</span><select v-model="idType" class="field"><option value="phone">{{ text('เบอร์โทรศัพท์','Phone number') }}</option><option value="national-id">{{ text('เลขบัตรประชาชน','National ID') }}</option></select></label><label class="grid gap-1 text-xs muted"><span>{{ text('เลข PromptPay','PromptPay ID') }}</span><input v-model="identifier" class="field" type="password" autocomplete="off" inputmode="numeric" maxlength="17" :placeholder="text('กรอกเพื่อสร้าง QR','Enter an ID for QR')"/></label></div><p class="mb-0 mt-2 text-xs muted">{{ text('QR จะใส่ยอดเงินของแต่ละคน ใช้กับผู้รับที่ทดสอบแล้วเท่านั้น ตรวจชื่อผู้รับและยอดในแอปธนาคารก่อนยืนยัน','Each QR includes the person’s amount. Check the recipient and amount in your banking app before confirming') }}</p></details>
    </fieldset></form>
    <p v-if="error||qrError" class="m-0 rounded-xl p-3 text-sm danger" style="background:var(--mh-danger-soft)" role="alert">{{ error||qrError }}</p>
    <p v-if="busy" class="muted text-sm" role="status">{{ text('กำลังสร้าง QR…','Generating QR…') }}</p><section v-if="result" class="grid gap-3"><article class="surface grid grid-cols-3 gap-2 p-4 text-sm"><div><span class="block text-xs muted">{{ text('ยอดบิล','Bill amount') }}</span><strong class="mono">{{ currency(result.amountMinor) }}</strong></div><div><span class="block text-xs muted">{{ text('ค่าบริการ + VAT','Service charge + VAT') }}</span><strong class="mono">{{ currency(result.serviceMinor+result.vatMinor) }}</strong></div><div><span class="block text-xs muted">{{ t('total') }}</span><strong class="mono accent">{{ currency(result.totalMinor) }}</strong></div></article><article v-for="person in result.people" :key="person.id" class="surface flex flex-wrap items-center gap-3 p-4"><span class="grid size-10 place-items-center rounded-xl" style="background:var(--mh-accent-soft);color:var(--mh-accent)"><UIcon name="i-lucide-user-round"/></span><span class="min-w-0 flex-1"><strong class="block truncate text-sm">{{ person.name||`คนที่ ${person.id}` }}</strong><small class="muted">{{ t('perPerson') }}</small></span><strong class="mono text-lg">{{ currency(person.amountMinor) }}</strong><div v-if="qrImages[person.id]" class="flex w-full items-center gap-3 border-t pt-3" style="border-color:var(--mh-line)"><img :src="qrImages[person.id]" alt="QR PromptPay" width="120" height="120" class="rounded-xl border"/><button class="btn-quiet text-xs" @click="download(qrImages[person.id]!,person.name)">{{ text('ดาวน์โหลด QR','Download QR') }}</button><span v-if="busy" class="text-xs muted">{{ text('กำลังสร้าง…','Generating…') }}</span></div></article><div class="flex flex-wrap gap-2"><button class="btn-quiet" :disabled="saved" @click="saveDraft"><UIcon name="i-lucide-save"/>{{ saved?text('บันทึกแล้ว','Saved'):text('บันทึกบิลไว้ในอุปกรณ์นี้','Save bill on this device') }}</button><button class="btn-quiet" @click="copyAmounts"><UIcon name="i-lucide-copy"/>{{ text('คัดลอกยอด','Copy amounts') }}</button></div></section>
    <section v-if="state.billDrafts.length" class="surface p-4"><h2 class="m-0 text-sm font-bold">{{ text('บิลที่บันทึกไว้ในอุปกรณ์','Bills saved on this device') }}</h2><div v-for="draft in [...state.billDrafts].reverse()" :key="draft.id" class="flex items-center gap-2 border-t" style="border-color:var(--mh-line)"><button class="flex min-h-12 min-w-0 flex-1 flex-wrap items-center justify-between gap-3 py-2 text-left text-sm" @click="restoreDraft(draft)"><span>{{ draft.title }} · {{ draft.people.length }} {{ text('คน','people') }}</span><span class="mono">{{ currency(draft.amountMinor) }}</span></button><button class="btn-quiet danger-action !px-3" :aria-label="text('ลบบิล','Remove bill')" @click="removeDraft(draft)"><UIcon name="i-lucide-x" class="size-4"/></button></div></section>
  </div>
</template>
